# Generated by Django 3.2.7 on 2021-09-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('sub_category', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateField()),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_image', models.ImageField(upload_to='', verbose_name='shop/media')),
            ],
        ),
    ]
